Change zsh

diff --git a/home/dot-zsh/functions/funcfresh b/home/dot-zsh/functions/funcfresh
--- a/home/dot-zsh/functions/funcfresh
+++ b/home/dot-zsh/functions/funcfresh
@@ -3,10 +3,10 @@
 ##? funcfresh - refresh function definition
 #function funcfresh {
 if ! (( $# )); then
-  echo >&2 "repo: Expecting function argument."
+  echo >&2 "funcfresh: Expecting function argument."
   return 1
 elif ! (( $+functions[$1] )); then
-  echo >&2 "repo: Function not found '$1'."
+  echo >&2 "funcfresh: Function not found '$1'."
   return 1
 fi
 unfunction $1
