Update repo function

diff --git a/.config/zsh/functions/repo b/.config/zsh/functions/repo
--- a/.config/zsh/functions/repo
+++ b/.config/zsh/functions/repo
@@ -1,130 +1,159 @@
 #!/bin/zsh
 ##? repo - Deal with git repos
 
-: ${REPO_HOME:=${XDG_CACHE_HOME:-$HOME/.cache}/repos}
+: ${ZPLUGINDIR:=${ZDOTDIR:-$HOME}/.zplugins}
+typeset -gHa _repo_zopts=(extended_glob no_monitor)
 
-function __repo_help {
+function -repo-help {
+  emulate -L zsh; setopt local_options $_repo_zopts
   echo "repo - Deal with git repos"
   echo ""
   echo "commands:"
-  echo "  help   print this help"
-  echo "  home   print repo home"
-  echo "  ls     print repo list"
-  echo "  rm     remove repo"
-  echo "  in     install repo"
-  echo "  up     update repos"
+  echo "  help                 print this help"
+  echo "  home                 print home for all repos"
+  echo "  list                 list repos"
+  echo "  path <REPO>          print repo path"
+  echo "  init <REPO>          print repo init file"
+  echo "  remove <REPOS...>    remove repos"
+  echo "  clone  <REPOS...>    clone repos"
+  echo "  update [<REPOS...>]  update repos"
   echo ""
   echo "examples:"
   echo "  repo in <repos.txt"
 }
 
-function __repo_update {
-  local repodir=$REPO_HOME/$1
-  local oldsha=$(command git -C $repodir rev-parse --short HEAD)
-  command git -C $repodir pull --quiet --ff --depth 1 --rebase --autostash
-  local newsha=$(command git -C $repodir rev-parse --short HEAD)
-  if [ $oldsha != $newsha ]; then
-    echo "Repo updated: "$1" ($oldsha->$newsha)"
+# Collect <redirected or piped| input
+function -repo-collect-input {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  printf '%s\n' "${@}"
+  if [[ ! -t 0 ]]; then
+    local data
+    while IFS= read -r data || [[ -n "$data" ]]; do
+      data=${data%\#*}
+      [[ -n "$data" ]] || continue
+      printf '%s\n' "$data"
+    done
   fi
 }
 
-function __repo_clone {
-  local repo=$1
-  local repodir=$REPO_HOME/$repo
-  if [ -d $repodir ]; then
-    echo "Found $repo..."
-    return
-  fi
+function -repo-home {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  echo $ZPLUGINDIR
+  [[ -d $ZPLUGINDIR ]] || return 1
+}
 
-  echo "Cloning $repo..."
-  command git clone --quiet --depth 1 --recursive --shallow-submodules \
-    https://github.com/$repo $repodir
+function -repo-path {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  (( $# )) || return 1
+  echo $ZPLUGINDIR/$1
+  [[ -d $ZPLUGINDIR/$1 ]] || return 1
+}
 
-  local init=$repodir/${repo:t}.plugin.zsh
-  if [[ ! -e $init ]]; then
-    local -a initfiles=($repodir/*.{plugin.zsh,zsh-theme,zsh,sh}(N))
-    (( $#initfiles )) && ln -sf $initfiles[1] $init
-  fi
-  if [[ $repo == sorin-ionescu/prezto ]]; then
-    for init in $repodir/modules/*/init.zsh; do
-      ln -sf $init $init:h/${init:h:t}.plugin.zsh
-    done
-  fi
-  echo "Cloned $repo."
+function -repo-init {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  (( $# )) || return 1
+  local -a initfiles=(
+    $ZPLUGINDIR/$1/${1:t}.plugin.zsh(N)
+    $ZPLUGINDIR/$1/*.{plugin.zsh,zsh-theme,zsh,sh}(N)
+    $ZPLUGINDIR/$1/${1:t}.plugin.zsh
+  )
+  echo $initfiles[1]
+  [[ -e $initfiles[1] ]] || return 1
+}
+
+function -repo-list {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  (( $# == 0 )) || return 1
+  local -a repos=($ZPLUGINDIR/*/*/.git(/N))
+  (( $#repos )) || return 1
+  for repo in $repos:A:h; do
+    echo ${repo:h:t}/${repo:t}
+  done
+}
+
+function -repo-update {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  (( $# )) || set -- $(-repo-list)
+  local repo repodir oldsha newsha err=0
+  for repo in $@; do
+    echo "Updating $repo..."
+    repodir=$ZPLUGINDIR/$repo
+    if [[ ! -d $repodir ]]; then
+      echo >&2 "ERROR: Repo not found '$repo'."
+      err=1
+      continue
+    fi
+    {
+      oldsha=$(command git -C $repodir rev-parse --short HEAD)
+      command git -C $repodir pull --quiet --ff --depth 1 --rebase --autostash
+      newsha=$(command git -C $repodir rev-parse --short HEAD)
+      if [[ $oldsha != $newsha ]]; then
+        echo "Repo updated '$repo': $oldsha->$newsha"
+        git -C $repodir --no-pager log --oneline --ancestry-path ${oldsha}..${newsha} 2>/dev/null
+      fi
+    } &
+  done
+  wait
+  echo "Repo updates complete."
+  return $err
+}
+
+function -repo-clone {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  local repo repodir
+  for repo in $@; do
+    repodir=$ZPLUGINDIR/$repo
+    if [[ -d $repodir ]]; then
+      echo "Found $repo..."
+    else
+      echo "Cloning $repo..."
+      {
+        command git clone --quiet --depth 1 --recursive --shallow-submodules \
+          https://github.com/$repo $repodir
+        echo "Clone complete '$repo'."
+      } &
+    fi
+  done
+  wait
+}
+
+function -repo-remove {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  local err=0
+  for repo in $@; do
+    if ! [[ "$ZPLUGINDIR" =~ $HOME/* ]]; then
+      echo >&2 "repo: \$ZPLUGINDIR not set correctly '$ZPLUGINDIR'."
+      return 2
+    elif [[ -d $ZPLUGINDIR/$repo ]]; then
+      command rm -rf -- $ZPLUGINDIR/$repo
+    else
+      echo "Repo not found '$repo'."
+      err=1
+    fi
+  done
+  return $err
 }
 
 function repo {
-  emulate -L zsh
-  setopt local_options extended_glob no_monitor
-
-  (( $# )) || {
+  emulate -L zsh; setopt local_options $_repo_zopts
+  if (( $# == 0 )); then
     echo >&2 "repo: Expecting command argument."
     return 1
-  }
+  fi
+
+  # collect piped and passed args
+  local -a args=("${(@f)$(-repo-collect-input "$@")}")
+  set -- $args
 
   local repo err=1
   local cmd=$1; shift
-
-  # piped/redirected input
-  if ! [ -t 0 ]; then
-    local -a args=($@)
-    local data
-    while IFS= read -r data || [ -n "$data" ]; do
-      data=${data%\#*}
-      args+=($data)
-    done
-    set -- $args
+  if (( ${+functions[-repo-$cmd]} )); then
+    -repo-$cmd $@
+  elif [[ "$cmd" == (-h|--help) ]]; then
+    -repo-help
+  else
+    echo >&2 "repo: Unknown command '"$cmd"'"
+    return 1
   fi
-
-  case "$cmd" in
-    help|-h|--help)
-      __repo_help
-    ;;
-    home)
-      echo $REPO_HOME
-    ;;
-    ls|list)
-      err=1
-      for repo in $REPO_HOME/*/*/.git(/N); do
-        echo ${repo:h:h:t}/${repo:h:t}
-        err=0
-      done
-      return $err
-    ;;
-    up|update)
-      echo "Checking for updates..."
-      for repo in $(repo ls); do
-        echo "$repo..."
-        __repo_update $repo &
-      done
-      wait
-      echo "Updates complete."
-    ;;
-    in|install)
-      for repo in $@; do
-        __repo_clone $repo &
-      done
-      wait
-    ;;
-    rm|del)
-      local err=0
-      for repo in $@; do
-        if ! [[ "$REPO_HOME" =~ $HOME/* ]]; then
-          echo >&2 "repo: \$REPO_HOME not set correctly '$REPO_HOME'."
-          return 2
-        elif ! [[ -d $REPO_HOME/$repo ]]; then
-          echo "Repo not found '$repo'."
-          err=1
-        else
-          command rm -rf -- $REPO_HOME/$repo
-        fi
-      done
-      return $err
-    ;;
-    *)
-      echo >&2 "repo: Unknown command '"$cmd"'"
-      return 1
-    ;;
-  esac
 }
 repo "$@"
